### ISSUE TITLE
Merge into monorepo

### ISSUE THREAD

**Issue by eemeli** [messageformat/loader#11]
Now that [messageformat/messageformat](https://github.com/messageformat/messageformat) is a monorepo containing multiple packages, we should also merge this loader there and archive this repo.

@cletusw would you be okay with that change? I can add you write access to the monorepo, but I'd need you to add me as a collaborator for `messageformat-loader` on npm to get Lerna's release tools to work properly.

**Comment by cletusw** [comment]
Added! Sounds good to me, thanks!
