### ISSUE TITLE
Work for js files

### ISSUE THREAD

**Issue by rightaway** [messageformat/loader#4]
Would it be possible to make this work for JS files rather than only JSON? If using the format described in http://messageformat.github.io/build/#other-javascript-build-environments.

**Comment by eemeli** [comment]
Maybe? JS files are fundamentally more complicated than JSON, so I'm not really sure quite how you imagine that'd work. It would help if you could draft out what sort of data format you had in mind, and how you'd like it to be loaded.

**Comment by rightaway** [comment]
Good point. There's many possible formats. As we get more experienced with using this package I could comment better later on, for example is it better to put each language in its own file, or put all languages together for each key and divide files based on its intention/usage in the application.

**Comment by eemeli** [comment]
The answers to those questions are likely to be rather dependent on your specific circumstances, but are unlikely to result in actual requirements that would not be satisfied by a data-only file format such as JSON. Messageformat is relatively easy to extend to work with other data formats -- see for instance [messageformat-yaml-loader](https://github.com/eemeli/messageformat-yaml-loader) and [messageformat-po-loader](https://github.com/eemeli/messageformat-po-loader) -- so if your particular format isn't yet supported, building tooling for it should not be too difficult.
