### ISSUE TITLE
Document Webpack 4 behavior

### ISSUE THREAD

**Issue by niksy** [messageformat/loader#8]
Since Webpack has full support for importing JSON files, passing messageformat JSON file through loader requires [additional Webpack configuration](https://github.com/niksy/loader) for it to work properly.

Example configuration should be:

```js
{
  test: /\bmessages\.json$/,
  loader: 'messageformat-loader',
  type: 'javascript/auto',
  options: {
    biDiSupport: false,
    disablePluralKeyChecks: false,
    formatters: null,
    intlSupport: false,
    locale: ['en'],
    strictNumberSign: false
  }
}
```

**Comment by eemeli** [comment]
You're right, that should be fixed. The docs got forgetten as we were fiddling with the implementation in #6. Care to send in a PR?
